### ISSUE TITLE
The target element stays focused after the label is being clicked

### ISSUE THREAD

**Issue by viftodi** [PolymerElements/iron-label#15] opened 2016-08-09 09:07 UTC
### Description

The target element stays focused after the label (of an iron-label) is  clicked
### Expected outcome
The target element should not remain focused after it is clicked via the iron-label

This behaviour is different than the one of a native label. 
A native label does not retain focus on the target element when it is clicked.
The native label and a native checkbox target does not retain focus when clicked on Chrome 51, Firefox 47, IE 11 and  Safari 9.
The native label with a native button target retains focus when the label is clicked on the chrome browser in my testing but not on Firefox and Safari. Haven't tested on IE yet. 
I would consider this a chrome bug.

This behaviour is also not consistent when using the builtin label for a paper-checkbox or paper-toggle button. When this label is clicked focus is not retained, while if you click the iron-label label, focus is being retained.

### Live Demo
In this demo I show the different scenarios and how the behavior of an iron-label is not consistent.
http://jsbin.com/vedofejezu/edit?html,output

### Browsers Affected
I haven't tested on all browsers but judging from the code there is no reason to believe that this does not affect all browsers as it's more of a functional error.

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [x] IE 11
- [ ] IE 10

**Comment by notwaldorf** [comment] 2016-08-09 19:37
As a general rule, please don't close and re-open an issue just to change the title -- the original conversation is now lost.

As I mentioned in https://github.com/PolymerElements/iron-label/issues/13#issuecomment-237982866, this is expected behaviour, and consistent with the native `<label`>. In your example, you're not styling the `<input type="checkbox>"` correctly -- for this element, a background or a simple border doesn't work.

If you use something like a ` box-shadow`, which does style native checkboxes, you'll notice the same behaviour: after you click the label, the element is focused: http://jsbin.com/bocenu/edit?html,output

Closing, as this is working as intended

**Closed by notwaldorf** 2016-08-09 19:37 UTC

**Comment by notwaldorf** [comment] 2016-08-09 19:39
JSBin that shows that styling checkboxes with backgrounds and borders doesn't work: http://jsbin.com/vagaqos/edit?html,output

**Comment by viftodi** [comment] 2016-08-10 08:09
Hello,

This seems to be the case for Chrome but not for Firefox or Safari, I have yet to test on IE.

How about the fact that a paper-checkbox/paper-toggle-button does not behave the same way with an iron-label as with the built-in label functionality as shown in the demo?

**Comment by 6palace** [comment] 2017-02-01 17:21
Hi, 

I am seeing this problem as well, the issue doesn't appear to be the focus state. When I click directly on a switch/checkbox, the round shadow transitions to disappear after mouseup. With a native label, the round shadow does not appear at all, which is fine. With iron-label, however, the shadow remains past the mouseup, until focus is dropped or the switch/checkbox is re-clicked. Is the shadow an outline around the button? If so, the transition to remove it is acting inconsistently.

Hope this helps.

**Comment by viftodi** [comment] 2017-02-01 17:38
Unfortunately @6palace My issue was closed, for some reason it was claimed that it's not an issue even if it clearly is an incongruity between using directly the label of paper-toggle-button or the label of an iron-label, and all this arose from my initial requirement to place the label on the left side

Oh well...

**Comment by 6palace** [comment] 2017-02-02 05:45
hahahahaha @viftodi it might be worth a couple-lines pull request. Glad I'm not the only one with the problem though.
